### ISSUE TITLE
Accessibility Review

### ISSUE THREAD

**Issue by schmelto** [AccessibleForAll/Support#25]
### Website URL

https://schmelto.github.io/Portfolio/

### GitHub Repo URL

https://github.com/schmelto/Portfolio

**Comment by emmalearnscode** [comment]
Thanks Tom for your submission! I've filmed my thoughts and will hopefully release the video in a couple of weeks. Here's some things to think about:

- A page should only have 1 h1 tag. To style the heading use spans and CSS instead of multiple h1s.
- h tags should only ever decrease by 1. In some places you jump from a h2 to a h5. Use styling to achieve the correct look instead of using smaller h tags.
- You should consider adding a prefers reduced motion media query for those that have issues with animation and movement on a website which pauses the animation at the top.
- Add a main tag around the main content instead of a div.
- Consider using articles and sections instead of so many divs
- Some of the colors you've chosen do not meet color contrast guidelines of 4.5: 1. against the white background. You should make these colors darker.
